"""
core/coverage_reporter.py — JARVIS V51.0 PROVING GROUND
Emits an ATT&CK Navigator layer (JSON) of JARVIS detection coverage from the
latest detection_harness results when available, else from the static set of
techniques the deployed detection modules cover. Writes
logs/attck_navigator_layer.json daily and on demand.
"""
from __future__ import annotations
import asyncio, json, logging, time
from pathlib import Path

logger = logging.getLogger("jarvis.coverage_reporter")

_OUT = Path("logs/attck_navigator_layer.json")
_INTERVAL = 24 * 3600

_STATIC = {
    "T1055": 100, "T1055.001": 100, "T1620": 100, "T1003": 100, "T1078": 75,
    "T1486": 100, "T1485": 75, "T1490": 50, "T1059.001": 100, "T1562.001": 75,
    "T1046": 100, "T1190": 50, "T1048": 75, "T1041": 50, "T1560": 75, "T1074": 75,
    "T1552": 75, "T1552.001": 75, "T1005": 75, "T1546": 75, "T1053": 75, "T1547": 75,
    "T1027": 50, "T1083": 75,
}


def _scores():
    try:
        from core import detection_harness as dh
        res = getattr(dh, "LAST_RESULTS", {}) or {}
        techs = res.get("techniques", {})
        if techs:
            merged = dict(_STATIC)
            for t, v in techs.items():
                merged[t] = 100 if v.get("detected") else 25
            return merged, "harness+static"
    except Exception:
        pass
    return dict(_STATIC), "static"


def _build_layer():
    scores, src = _scores()
    techniques = [{"techniqueID": t, "score": s,
                   "color": "", "comment": f"JARVIS coverage ({src})"}
                  for t, s in sorted(scores.items())]
    return {
        "name": "JARVIS Detection Coverage",
        "versions": {"layer": "4.5", "navigator": "4.9.1", "attack": "15"},
        "domain": "enterprise-attack",
        "description": f"Auto-generated by coverage_reporter ({src}) at {int(time.time())}",
        "gradient": {"colors": ["#ff6666", "#ffe766", "#8ec843"], "minValue": 0, "maxValue": 100},
        "techniques": techniques,
    }


def _write():
    try:
        _OUT.parent.mkdir(parents=True, exist_ok=True)
        _OUT.write_text(json.dumps(_build_layer(), indent=2), encoding="utf-8")
        logger.info("coverage_reporter: Navigator layer written %s (%d techniques)",
                    _OUT, len(_build_layer()["techniques"]))
        return str(_OUT)
    except Exception as e:
        logger.error("coverage_reporter: write failed: %s", e)
        return None


async def generate(correlator=None):
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _write)


async def start(correlator=None):
    if correlator is not None and hasattr(correlator, "register_responder"):
        try:
            correlator.register_responder("coverage_reporter", generate)
        except Exception:
            pass
    logger.info("COVERAGE_REPORTER: armed — Navigator layer every %dh", _INTERVAL // 3600)
    while True:
        try:
            await generate(correlator)
        except Exception as e:
            logger.debug("coverage_reporter: cycle error: %s", e)
        await asyncio.sleep(_INTERVAL)
