"""core/deployment_planner.py — V69 M60.5: read-only Windows deployment planning.

THIS MODULE MUTATES NOTHING. EVER.
----------------------------------
It inspects the current interpreter, virtual environment, repository and managed
directories, probes whether the configured Ollama host is reachable (a plain TCP
connect, no request, no model), and RENDERS a plan describing what an operator would
have to do to launch JARVIS a given way. It does not install a service, create a
scheduled task, add a startup entry, touch the registry, change an environment
variable, grant a privilege, open a firewall port or restart anything — and there is
no code path in this file that could, because it imports no mutation API at all.

WHY A PLANNER AND NOT A DEPLOYER
--------------------------------
M60's assignment explicitly forbids installing a service, a scheduled task or a
startup entry. But the reliability question "would this survive a reboot, and what
exactly would it run?" is real, and answering it from memory is how deployment
mistakes happen. A DETERMINISTIC plan — exact executable, exact working directory,
exact arguments, exact data/log paths, required privileges, risks, rollback — lets the
operator perform the change themselves with full knowledge.

TEMPLATE DISCIPLINE
-------------------
Any command text a plan shows comes from a FIXED template in this module with
validated substitutions (an existing filesystem path, a fixed flag). No template is
generated by a model, none is assembled from operator free text, and every plan
carries ``apply_supported = False`` — there is no apply path in M60.
"""
from __future__ import annotations

import os
import shutil
import socket
import sys
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

from core.managed_paths import app_root, backups_dir, data_dir, diagnostics_dir

# Probe bound: a planner may never hang the console on an unreachable host.
_PROBE_TIMEOUT_S = 0.6


class DeploymentTarget(str, Enum):
    """The closed set of plannable launch mechanisms."""

    INTERACTIVE_TERMINAL = "INTERACTIVE_TERMINAL"
    STARTUP_APPLICATION = "STARTUP_APPLICATION"
    TASK_SCHEDULER_PLAN = "TASK_SCHEDULER_PLAN"
    WINDOWS_SERVICE_PLAN = "WINDOWS_SERVICE_PLAN"


class PlanFeasibility(str, Enum):
    READY = "READY"                     # every precondition satisfied
    READY_WITH_WARNINGS = "READY_WITH_WARNINGS"
    BLOCKED = "BLOCKED"                 # a precondition cannot be met as inspected


@dataclass
class EnvironmentFacts:
    """Everything the planner INSPECTED. Read-only, bounded, home-path free."""

    python_executable: str = ""
    python_version: str = ""
    in_virtualenv: bool = False
    venv_name: str = ""
    repo_root_name: str = ""
    repo_exists: bool = False
    entrypoint_exists: bool = False
    data_writable: bool = False
    logs_writable: bool = False
    ollama_host: str = ""
    ollama_reachable: bool = False
    is_windows: bool = False
    is_admin: bool = False
    pythonw_available: bool = False
    user_present: bool = False

    def snapshot(self) -> dict:
        return dict(self.__dict__)


@dataclass
class DeploymentPlan:
    """One rendered plan. ``apply_supported`` is False for every target in M60."""

    target: DeploymentTarget
    feasibility: PlanFeasibility = PlanFeasibility.READY
    executable: str = ""
    arguments: list[str] = field(default_factory=list)
    working_directory: str = ""
    data_paths: list[str] = field(default_factory=list)
    log_paths: list[str] = field(default_factory=list)
    requires_admin: bool = False
    required_permissions: list[str] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)
    rollback_steps: list[str] = field(default_factory=list)
    manual_steps: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    apply_supported: bool = False
    dry_run: bool = True
    host_changes: int = 0               # STRUCTURALLY always 0

    def snapshot(self, *, redact_home: bool = False) -> dict:
        """Plan as a dict. ``redact_home=True`` for anything that LEAVES the host.

        The interactive panel deliberately shows the real executable path — a plan
        the operator cannot copy is useless, and it is their own console. A
        diagnostics bundle is a different audience, so it takes the redacted form.
        """
        def _p(value: str) -> str:
            if not redact_home:
                return value
            from core.redaction_policy import redact_home_paths
            return redact_home_paths(value)[0]

        return {
            "target": self.target.value, "feasibility": self.feasibility.value,
            "executable": _p(self.executable),
            "arguments": [_p(a) for a in self.arguments],
            "working_directory": _p(self.working_directory),
            "data_paths": list(self.data_paths), "log_paths": list(self.log_paths),
            "requires_admin": self.requires_admin,
            "required_permissions": list(self.required_permissions),
            "risks": list(self.risks),
            "rollback_steps": [_p(s) for s in self.rollback_steps],
            "manual_steps": [_p(s) for s in self.manual_steps],
            "warnings": list(self.warnings),
            "apply_supported": self.apply_supported, "dry_run": self.dry_run,
            "host_changes": self.host_changes,
        }


# ══════════════════════════════════════════════════════════════════════════════
#  Inspection (read-only)
# ══════════════════════════════════════════════════════════════════════════════
def _writable(path: Path) -> bool:
    """Is this directory writable? Answered with ``os.access``, not by writing."""
    try:
        return path.is_dir() and os.access(str(path), os.W_OK)
    except OSError:
        return False


def _is_admin() -> bool:
    """Report whether the process is elevated. READ-ONLY: never requests elevation."""
    try:
        if os.name == "nt":
            import ctypes
            return bool(ctypes.windll.shell32.IsUserAnAdmin())
        return os.geteuid() == 0            # type: ignore[attr-defined]
    except Exception:  # noqa: BLE001
        return False


def _probe_host(host_url: str) -> bool:
    """A bounded TCP connect to the configured Ollama host. No request is sent, no
    model is touched, no configuration is read or changed."""
    try:
        raw = str(host_url or "").strip()
        if not raw:
            return False
        rest = raw.split("://", 1)[-1].split("/", 1)[0]
        if ":" in rest:
            host, _, port_s = rest.rpartition(":")
            port = int(port_s)
        else:
            host, port = rest, 11434
        with socket.create_connection((host or "127.0.0.1", port),
                                      timeout=_PROBE_TIMEOUT_S):
            return True
    except (OSError, ValueError):
        return False


def inspect_environment(*, probe_ollama: bool = True) -> EnvironmentFacts:
    """Gather every fact a plan needs. Pure inspection — nothing is created."""
    root = app_root()
    facts = EnvironmentFacts(
        python_executable=sys.executable or "",
        python_version=f"{sys.version_info.major}.{sys.version_info.minor}."
                       f"{sys.version_info.micro}",
        in_virtualenv=bool(getattr(sys, "base_prefix", sys.prefix) != sys.prefix),
        repo_root_name=root.name,
        repo_exists=root.is_dir(),
        entrypoint_exists=(root / "main.py").is_file(),
        is_windows=(os.name == "nt"),
        is_admin=_is_admin(),
        user_present=bool(os.environ.get("USERNAME") or os.environ.get("USER")),
    )
    if facts.in_virtualenv:
        facts.venv_name = Path(sys.prefix).name
    facts.data_writable = _writable(data_dir())
    facts.logs_writable = _writable(root / "logs") or _writable(root)
    exe_dir = Path(sys.executable).parent if sys.executable else None
    if exe_dir is not None:
        facts.pythonw_available = (exe_dir / "pythonw.exe").is_file()
    if not facts.pythonw_available:
        facts.pythonw_available = shutil.which("pythonw") is not None
    try:
        # The existing single resolver (M55). The planner READS the configured host;
        # it never writes an Ollama setting and never sends a request to one.
        from core.ollama_native import default_base_url
        facts.ollama_host = str(default_base_url() or "")
    except Exception:  # noqa: BLE001
        facts.ollama_host = ""
    if probe_ollama and facts.ollama_host:
        facts.ollama_reachable = _probe_host(facts.ollama_host)
    return facts


# ══════════════════════════════════════════════════════════════════════════════
#  Fixed, deterministic templates (never model-generated)
# ══════════════════════════════════════════════════════════════════════════════
# Placeholders are substituted with INSPECTED filesystem paths only. There is no
# operator-supplied text anywhere in these strings.
_TPL_SHORTCUT = (
    'Create a shortcut in the per-user Startup folder whose Target is '
    '"{exe}" "{entry}" and whose "Start in" is "{cwd}".'
)
_TPL_SCHTASKS = (
    'schtasks /Create /TN JARVIS /TR "\\"{exe}\\" \\"{entry}\\"" '
    '/SC ONLOGON /RL LIMITED'
)
_TPL_SC = (
    'sc create JARVIS binPath= "\\"{wrapper}\\" \\"{entry}\\"" '
    'start= delayed-auto obj= LocalSystem'
)
_TPL_ROLLBACK_SHORTCUT = "Delete the shortcut from the Startup folder."
_TPL_ROLLBACK_SCHTASKS = "schtasks /Delete /TN JARVIS /F"
_TPL_ROLLBACK_SC = "sc delete JARVIS"


def _common_paths() -> tuple[list[str], list[str]]:
    root = app_root()
    data = [str(data_dir(create=False).relative_to(root)),
            str(backups_dir(create=False).relative_to(root)),
            str(diagnostics_dir(create=False).relative_to(root))]
    logs = ["logs", "logs/journals"]
    return data, logs


def _base_plan(target: DeploymentTarget, facts: EnvironmentFacts) -> DeploymentPlan:
    root = app_root()
    data, logs = _common_paths()
    plan = DeploymentPlan(
        target=target,
        executable=facts.python_executable,
        arguments=[str(root / "main.py")],
        working_directory=str(root),
        data_paths=data, log_paths=logs,
    )
    if not facts.repo_exists or not facts.entrypoint_exists:
        plan.feasibility = PlanFeasibility.BLOCKED
        plan.warnings.append("repository entrypoint main.py was not found")
    if not facts.python_executable:
        plan.feasibility = PlanFeasibility.BLOCKED
        plan.warnings.append("python executable could not be resolved")
    if not facts.in_virtualenv:
        plan.warnings.append("not running inside a virtual environment")
    if not facts.data_writable:
        plan.warnings.append("managed data directory is not writable")
    if facts.ollama_host and not facts.ollama_reachable:
        plan.warnings.append("configured Ollama host did not answer a TCP probe")
    if not facts.is_windows and target is not DeploymentTarget.INTERACTIVE_TERMINAL:
        plan.warnings.append("target host is not Windows; plan is informational")
    return plan


def _finalize(plan: DeploymentPlan) -> DeploymentPlan:
    if plan.feasibility is not PlanFeasibility.BLOCKED and plan.warnings:
        plan.feasibility = PlanFeasibility.READY_WITH_WARNINGS
    plan.apply_supported = False
    plan.dry_run = True
    plan.host_changes = 0
    return plan


def plan_interactive_terminal(facts: EnvironmentFacts) -> DeploymentPlan:
    plan = _base_plan(DeploymentTarget.INTERACTIVE_TERMINAL, facts)
    plan.required_permissions = ["current user"]
    plan.risks = ["session ends when the terminal closes",
                  "no automatic restart after a reboot"]
    plan.manual_steps = [f'cd "{plan.working_directory}"',
                         f'"{plan.executable}" main.py']
    plan.rollback_steps = ["close the terminal window"]
    return _finalize(plan)


def plan_startup_application(facts: EnvironmentFacts) -> DeploymentPlan:
    plan = _base_plan(DeploymentTarget.STARTUP_APPLICATION, facts)
    plan.required_permissions = ["current user (per-user Startup folder)"]
    plan.risks = [
        "starts only after interactive logon",
        "a console window appears unless pythonw is used",
        "an interactive console is required for HITL and barge-in",
    ]
    plan.manual_steps = [_TPL_SHORTCUT.format(
        exe=plan.executable, entry=plan.arguments[0], cwd=plan.working_directory)]
    plan.rollback_steps = [_TPL_ROLLBACK_SHORTCUT]
    if not facts.pythonw_available:
        plan.warnings.append("pythonw.exe not found; the console window will show")
    return _finalize(plan)


def plan_task_scheduler(facts: EnvironmentFacts) -> DeploymentPlan:
    plan = _base_plan(DeploymentTarget.TASK_SCHEDULER_PLAN, facts)
    plan.required_permissions = ["current user", "Task Scheduler write access"]
    plan.risks = [
        "a task running without an interactive desktop cannot show HITL prompts",
        "voice input and TTS are unavailable in a non-interactive session",
        "ONLOGON keeps the task in the user session; ONSTART would not",
    ]
    plan.manual_steps = [_TPL_SCHTASKS.format(
        exe=plan.executable, entry=plan.arguments[0])]
    plan.rollback_steps = [_TPL_ROLLBACK_SCHTASKS]
    plan.warnings.append("M60 does not create scheduled tasks; this is a plan only")
    return _finalize(plan)


def plan_windows_service(facts: EnvironmentFacts) -> DeploymentPlan:
    plan = _base_plan(DeploymentTarget.WINDOWS_SERVICE_PLAN, facts)
    plan.requires_admin = True
    plan.required_permissions = ["Administrator", "SeCreateServicePrivilege"]
    plan.risks = [
        "Python is not a Windows service binary; a service wrapper is required",
        "session 0 isolation removes the console, HITL, barge-in, audio and TTS",
        "LocalSystem would run JARVIS with far more privilege than it needs",
        "an unattended service could act without an operator present",
    ]
    plan.manual_steps = [_TPL_SC.format(wrapper="<service-wrapper.exe>",
                                        entry=plan.arguments[0])]
    plan.rollback_steps = [_TPL_ROLLBACK_SC]
    plan.warnings.append("M60 does not install services; this is a plan only")
    if not facts.is_admin:
        plan.warnings.append("current process is not elevated; the plan would fail")
    return _finalize(plan)


_PLANNERS = {
    DeploymentTarget.INTERACTIVE_TERMINAL: plan_interactive_terminal,
    DeploymentTarget.STARTUP_APPLICATION: plan_startup_application,
    DeploymentTarget.TASK_SCHEDULER_PLAN: plan_task_scheduler,
    DeploymentTarget.WINDOWS_SERVICE_PLAN: plan_windows_service,
}


def build_plan(target: DeploymentTarget,
               facts: EnvironmentFacts | None = None) -> DeploymentPlan:
    """Build ONE plan for a target from the closed planner map."""
    f = facts if facts is not None else inspect_environment()
    return _PLANNERS[target](f)


# ══════════════════════════════════════════════════════════════════════════════
#  Rendering (ASCII, bounded, home-path free)
# ══════════════════════════════════════════════════════════════════════════════
def _short(path: str) -> str:
    """Render a path relative to the app root where possible, so a panel never
    prints the operator's home directory."""
    try:
        return str(Path(path).resolve().relative_to(app_root().parent))
    except (ValueError, OSError):
        return Path(path).name or str(path)


def render_deployment_status(facts: EnvironmentFacts | None = None,
                             *, language: str = "es") -> str:
    english = str(language or "es").lower().startswith("en")
    f = facts if facts is not None else inspect_environment()
    rows = [
        ("python", f.python_version),
        ("executable", _short(f.python_executable)),
        ("virtualenv", "yes" if f.in_virtualenv else "no"),
        ("repo", f.repo_root_name),
        ("entrypoint", "yes" if f.entrypoint_exists else "no"),
        ("data_writable", "yes" if f.data_writable else "no"),
        ("logs_writable", "yes" if f.logs_writable else "no"),
        ("ollama_reachable", "yes" if f.ollama_reachable else "no"),
        ("windows", "yes" if f.is_windows else "no"),
        ("elevated", "yes" if f.is_admin else "no"),
    ]
    title = "DEPLOYMENT STATUS" if english else "ESTADO DE DESPLIEGUE"
    lines = [title] + [f"  {k}={v}" for k, v in rows]
    note = ("read-only inspection; no host change was made" if english
            else "inspeccion de solo lectura; no se modifico el host")
    lines.append(f"  ({note})")
    return "\n".join(lines)


def render_plan(plan: DeploymentPlan, *, language: str = "es",
                redact_home: bool = False) -> str:
    """Render a plan. ``redact_home=True`` is for output that leaves this host.

    The default is False on purpose: the interactive panel prints the operator's own
    paths so the manual steps are copy-pasteable. Nothing else in M60 renders a plan
    with the default — the diagnostics bundle uses ``snapshot(redact_home=True)``.
    """
    english = str(language or "es").lower().startswith("en")
    title = "DEPLOYMENT PLAN" if english else "PLAN DE DESPLIEGUE"
    if redact_home:
        from core.redaction_policy import redact_home_paths

        def _h(value: str) -> str:
            return redact_home_paths(str(value))[0]
    else:
        def _h(value: str) -> str:
            return str(value)
    lines = [
        f"{title} [{plan.target.value}]",
        f"  feasibility={plan.feasibility.value}",
        f"  dry_run={'yes' if plan.dry_run else 'no'}",
        f"  apply_supported={'yes' if plan.apply_supported else 'no'}",
        f"  host_changes={plan.host_changes}",
        f"  executable={_h(_short(plan.executable))}",
        f"  arguments={' '.join(_h(_short(a)) for a in plan.arguments)}",
        f"  working_directory={_h(_short(plan.working_directory))}",
        f"  data_paths={','.join(plan.data_paths)}",
        f"  log_paths={','.join(plan.log_paths)}",
        f"  requires_admin={'yes' if plan.requires_admin else 'no'}",
        f"  permissions={'; '.join(plan.required_permissions)}",
    ]
    for risk in plan.risks[:6]:
        lines.append(f"  risk: {risk}")
    for warn in plan.warnings[:6]:
        lines.append(f"  warning: {warn}")
    for step in plan.manual_steps[:4]:
        lines.append(f"  manual: {_h(step)}")
    for step in plan.rollback_steps[:4]:
        lines.append(f"  rollback: {_h(step)}")
    note = ("nothing was installed, scheduled or registered" if english
            else "no se instalo, programo ni registro nada")
    lines.append(f"  ({note})")
    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
#  M60.5.1 — exact read-only commands
# ══════════════════════════════════════════════════════════════════════════════
_DEPLOY_ALIASES: dict[str, "DeploymentTarget | None"] = {
    "/deployment-status": None,
    "/estado-despliegue": None,
    "/deployment-plan terminal": DeploymentTarget.INTERACTIVE_TERMINAL,
    "/deployment-plan startup": DeploymentTarget.STARTUP_APPLICATION,
    "/deployment-plan scheduler": DeploymentTarget.TASK_SCHEDULER_PLAN,
    "/deployment-plan service": DeploymentTarget.WINDOWS_SERVICE_PLAN,
    "/plan-despliegue terminal": DeploymentTarget.INTERACTIVE_TERMINAL,
    "/plan-despliegue arranque": DeploymentTarget.STARTUP_APPLICATION,
    "/plan-despliegue programador": DeploymentTarget.TASK_SCHEDULER_PLAN,
    "/plan-despliegue servicio": DeploymentTarget.WINDOWS_SERVICE_PLAN,
}


def parse_deployment_command(text: str) -> "tuple[bool, DeploymentTarget | None]":
    """Return ``(recognised, target)``. ``target is None`` means status.

    ``/deployment-plan terminal`` is ONE literal alias, not a verb plus an argument:
    there is no argument parsing, so no plan name, path or flag can arrive from free
    text and ``/deployment-plan C:\\evil`` is an ordinary conversational turn.
    """
    raw = " ".join((text or "").strip().lower().split())
    if not raw or not raw.startswith("/") or raw not in _DEPLOY_ALIASES:
        return False, None
    return True, _DEPLOY_ALIASES[raw]


def known_deployment_aliases() -> tuple[str, ...]:
    return tuple(sorted(_DEPLOY_ALIASES))


def apply_deployment_command(target: "DeploymentTarget | None", *,
                             language: str = "es",
                             facts: EnvironmentFacts | None = None) -> str:
    """Render the requested read-only panel. Never mutates the host; never raises."""
    try:
        f = facts if facts is not None else inspect_environment()
        if target is None:
            return render_deployment_status(f, language=language)
        return render_plan(build_plan(target, f), language=language)
    except Exception as exc:  # noqa: BLE001
        return f"DEPLOYMENT: {type(exc).__name__}"
